services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.lenient
    ports:
      - "3000:80"
    environment:
      - SUPABASE_URL=https://eiktdiiziwesatueiyht.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpa3RkaWl6aXdlc2F0dWVpeWh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNDQ4ODIsImV4cCI6MjA2NzkyMDg4Mn0.YpMFYilCeBY6nuhJPB_HiiqvNIhi0zULyRwjcbhx-yU
    networks:
      - zengineer-network

networks:
  zengineer-network:
    driver: bridge
